name: Java CD with ssh

on:
    push:
        branches: ["develop"]

permissions:
    contents: read

jobs:
    ssh:
        runs-on: ubuntu-latest

        steps:
            - name: jenkins-curl
              run: |
                  curl  --insecure  --location 'https://jenkins.next.jaehan1346dev.online/job/typeit-admin/build?token=outCall' --header 'Content-Type: application/json' --header 'Authorization: ${{ secrets.TYPEIT_API_JENKINS_AUTH_BASIC_TOKEN }}' --data-raw '{ "email": "jaehan1346@nextinnovation.kr" }'

