name: Java CD with ssh

on:
    push:
        branches: ["develop"]

permissions:
    contents: read

jobs:
    ssh:
        runs-on: ubuntu-latest

        steps:
            - name: jenkins-curl
              run: |
                  curl --location 'https://jenkins.next.jaehan1346dev.online/job/typeit-api/build?token=outCall' --header 'Content-Type: application/json' --header 'Authorization: Basic amFlaGFuMTM0NjoxMWIyZmU5MTFiN2U4Y2NhYjFjYmEyMjQ2NzBkOTUwY2M1' --data-raw '{"email": "jaehan1346@gmail.com"}'
                      
